### ISSUE TITLE
Request feature of printing pattern index at simulation output.

### ISSUE THREAD

**Issue by YanjenChen** [ric2k1/gv0-socv#2]
The current output of the simulation result only provides the number of cycles, which is hard to understand what is the current input pattern.
Can we add information about the input pattern to the output? Such as the following example:
```
==========================================
= cycle XX      pattern YY
==========================================
```
This will help users to easily observe the change due to the input.

**Comment by HHHUUUGGGOOO** [comment]
Yes, sure! Thanks for your suggestion! We'll add the feature in GV, and will announce students to "git pull" in the following homework!
