### ISSUE TITLE
`BREPort` reports error after executing`BCONstruct`.

### ISSUE THREAD

**Issue by YanjenChen** [ric2k1/gv0-socv#7]
The behavior of the reference program "gvbddv-ref-linux" seems weird when entering the following commands.
```
read design -v tests/b.v
blast ntk
breset 2000 8009 30011
bsetorder -file
print aig -PO
bcon -n 205
brep 205
```
`BREPort` reports `[ERROR]: Illegal option "205" !!`. However, net 205 has been built in the previous command.

With the following commands, I can successfully print net 205.
```
read design -v tests/b.v
blast ntk
breset 2000 8009 30011
bsetorder -file
print aig -PO
bcon -a
brep 205
```

Comparing these two sets of commands, I think something went wrong in the given `GVNtkMgr::dfsOrder` function.

**Comment by YanjenChen** [comment]
Using `print aig -PO` command, it is clear that net 205 is a PO.
```
yosysSETUP> print aig -PO

PO :
PO #    0 : net name =                p1[0] net id =        202
PO #    1 : net name =                p2[0] net id =        203
PO #    2 : net name =                p3[0] net id =        204
PO #    3 : net name =                p4[0] net id =        205
PO #    4 : net name =                p5[0] net id =        206
PO #    5 : net name =         time_left[0] net id =        207
PO #    6 : net name =         time_left[1] net id =        208
PO #    7 : net name =         time_left[2] net id =        209
PO #    8 : net name =         time_left[3] net id =        210
PO #    9 : net name =         time_left[4] net id =        211
PO #   10 : net name =         time_left[5] net id =        212
PO #   11 : net name =         time_left[6] net id =        213
PO #   12 : net name =         time_left[7] net id =        214
```

However, the gate type of net 205 in `GVNtkMgr` is 6 (a.k.a. `GV_NTK_OBJ_AND`).
```
yosysSETUP> bcon -n 205
Call 205, type 6
```

If we further look into `GVNtkMgr::dfsOrder` function:
```c++
// Put fanins of a net (id) into a vector (nets) in topological order
void
GVNtkMgr::dfsOrder(const GVNetId& id, vector<GVNetId>& nets) {
    if (isLatestMiscData(id)) return;

    setLatestMiscData(id);
    //  traverse fanin logics
    const GV_Ntk_Type_t type = getGateType(id);
    gvMsg(GV_MSG_IFO) << "Call " << id.id << ", type " << type << endl;
    if ((type == GV_NTK_OBJ_FF_NS) || (type == GV_NTK_OBJ_PO)) {
        dfsOrder(getInputNetId(id, 0), nets);
    } else if (type == GV_NTK_OBJ_AIG) {
        dfsOrder(getInputNetId(id, 0), nets);
        dfsOrder(getInputNetId(id, 1), nets);
    }
    nets.push_back(id); // Record Order
}
```
Only `GV_NTK_OBJ_FF_NS`, `GV_NTK_OBJ_PO`, and `GV_NTK_OBJ_AIG` will trigger the recursion. Therefore, if we pass net 205 to this function, DFS will not behave correctly.

I think this is a critical bug. This bug seriously affects our development of HW3 because we expect the given netlist to be parsed correctly.

**Comment by HHHUUUGGGOOO** [comment]
Hi, 

Sorry for your inconvenience. You need to use "bconstruct -o" rather than "bconstruct -n" to construct PO node. 

In this command, "PO nodes (output)" and "internal nodes (net)" needs to be separated. And we have updated command to make "bconstruct -n" allow to input PO nodes, since it is also true to say PO is a net (wire). 

![Screen Shot 2023-04-15 at 8 19 49 PM](https://user-images.githubusercontent.com/45988775/232223116-c84e3a83-e0b4-4d56-860a-4334f2468996.png)
